# See:
#   - https://developers.openai.com/codex/local-config#cli
#   - https://github.com/openai/codex/blob/main/docs/config.md
check_for_update_on_startup = true
file_opener = "cursor"
model = "gpt-5.1-codex-max"
model_reasoning_effort = "xhigh"

[features]
  ghost_commit = true
  web_search_request = true

[mcp_servers.context7]
  args = ["-y", "@upstash/context7-mcp", "--api-key", "$API_KEY_CONTEXT7_MCP"]
  command = "npx"

  # [mcp_servers.playwright]
  #   args = ["@playwright/mcp@latest", "--extension"]
  #   command = "npx"
  #   env_vars = ["PLAYWRIGHT_MCP_EXTENSION_TOKEN"]

  # [mcp_servers.next-devtools]
  #   args = ["next-devtools-mcp@latest"]
  #   command = "npx"

[mcp_servers.sequential-thinking]
  args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
  command = "npx"

[notice]
  "hide_gpt-5.1-codex-max_migration_prompt" = true
  hide_gpt5_1_migration_prompt = true

[shell_environment_policy]
  ignore_default_excludes = true
