[mcp_servers.context7]
  args = ["-y", "@upstash/context7-mcp"]
  command = "npx"

[mcp_servers.playwright]
  args = ["@playwright/mcp@latest", "--extension"]
  command = "npx"
  env = { PLAYWRIGHT_MCP_EXTENSION_TOKEN = "K_oz-KHGYUWYSS9Ps_QsOcmOmtX-qhrH0fWxC2CjdFA" }

[mcp_servers.next-devtools]
  args = ["next-devtools-mcp@latest"]
  command = "npx"

[mcp_servers.sequential-thinking]
  args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
  command = "npx"
