[mcp_servers.context7]
  args = ["-y", "@upstash/context7-mcp"]
  command = "npx"

[mcp_servers.next-devtools]
  args = ["next-devtools-mcp@latest"]
  command = "npx"

[mcp_servers.sequential-thinking]
  args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
  command = "npx"

[projects."/Users/prb/Sablier/indexers"]
  trust_level = "trusted"

[projects."/Users/prb/.codex"]
  trust_level = "trusted"

[projects."/Users/prb/Sablier/ui/interfaces"]
  trust_level = "trusted"
